/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTcgRouteImport } from './routes/api/public/tcg'
import { Route as ApiPublicPokeRadioRouteImport } from './routes/api/public/poke-radio'
import { Route as ApiPublicMcpRouteImport } from './routes/api/public/mcp'
import { Route as ApiPublicEbaySoldRouteImport } from './routes/api/public/ebay-sold'
import { Route as ApiPublicCardPricesRouteImport } from './routes/api/public/card-prices'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTcgRoute = ApiPublicTcgRouteImport.update({
  id: '/api/public/tcg',
  path: '/api/public/tcg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPokeRadioRoute = ApiPublicPokeRadioRouteImport.update({
  id: '/api/public/poke-radio',
  path: '/api/public/poke-radio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMcpRoute = ApiPublicMcpRouteImport.update({
  id: '/api/public/mcp',
  path: '/api/public/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEbaySoldRoute = ApiPublicEbaySoldRouteImport.update({
  id: '/api/public/ebay-sold',
  path: '/api/public/ebay-sold',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCardPricesRoute = ApiPublicCardPricesRouteImport.update({
  id: '/api/public/card-prices',
  path: '/api/public/card-prices',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/public/card-prices': typeof ApiPublicCardPricesRoute
  '/api/public/ebay-sold': typeof ApiPublicEbaySoldRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/poke-radio': typeof ApiPublicPokeRadioRoute
  '/api/public/tcg': typeof ApiPublicTcgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/public/card-prices': typeof ApiPublicCardPricesRoute
  '/api/public/ebay-sold': typeof ApiPublicEbaySoldRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/poke-radio': typeof ApiPublicPokeRadioRoute
  '/api/public/tcg': typeof ApiPublicTcgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/public/card-prices': typeof ApiPublicCardPricesRoute
  '/api/public/ebay-sold': typeof ApiPublicEbaySoldRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/poke-radio': typeof ApiPublicPokeRadioRoute
  '/api/public/tcg': typeof ApiPublicTcgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/public/card-prices'
    | '/api/public/ebay-sold'
    | '/api/public/mcp'
    | '/api/public/poke-radio'
    | '/api/public/tcg'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/public/card-prices'
    | '/api/public/ebay-sold'
    | '/api/public/mcp'
    | '/api/public/poke-radio'
    | '/api/public/tcg'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/public/card-prices'
    | '/api/public/ebay-sold'
    | '/api/public/mcp'
    | '/api/public/poke-radio'
    | '/api/public/tcg'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiPublicCardPricesRoute: typeof ApiPublicCardPricesRoute
  ApiPublicEbaySoldRoute: typeof ApiPublicEbaySoldRoute
  ApiPublicMcpRoute: typeof ApiPublicMcpRoute
  ApiPublicPokeRadioRoute: typeof ApiPublicPokeRadioRoute
  ApiPublicTcgRoute: typeof ApiPublicTcgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tcg': {
      id: '/api/public/tcg'
      path: '/api/public/tcg'
      fullPath: '/api/public/tcg'
      preLoaderRoute: typeof ApiPublicTcgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/poke-radio': {
      id: '/api/public/poke-radio'
      path: '/api/public/poke-radio'
      fullPath: '/api/public/poke-radio'
      preLoaderRoute: typeof ApiPublicPokeRadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mcp': {
      id: '/api/public/mcp'
      path: '/api/public/mcp'
      fullPath: '/api/public/mcp'
      preLoaderRoute: typeof ApiPublicMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ebay-sold': {
      id: '/api/public/ebay-sold'
      path: '/api/public/ebay-sold'
      fullPath: '/api/public/ebay-sold'
      preLoaderRoute: typeof ApiPublicEbaySoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/card-prices': {
      id: '/api/public/card-prices'
      path: '/api/public/card-prices'
      fullPath: '/api/public/card-prices'
      preLoaderRoute: typeof ApiPublicCardPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiPublicCardPricesRoute: ApiPublicCardPricesRoute,
  ApiPublicEbaySoldRoute: ApiPublicEbaySoldRoute,
  ApiPublicMcpRoute: ApiPublicMcpRoute,
  ApiPublicPokeRadioRoute: ApiPublicPokeRadioRoute,
  ApiPublicTcgRoute: ApiPublicTcgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
